# -*- coding: utf-8 -*-
"""20200826_yolo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o3mLSdx8nm4m2qVViaxJtwLFRasmPrOB
"""

!nvidia-smi

! git clone https://github.com/pjreddie/darknet.git

! cd darknet; head Makefile

! cd darknet; head Makefile

!sed -i "s/GPU=0/GPU=1/g" darknet/Makefile
!sed -i "s/CUDNN=0/CUDNN=1/g" darknet/Makefile
!sed -i "s/OPENCV=0/OPENCV=1/g" darknet/Makefile

! cd darknet; make

! cd darknet; ./darknet

!wget https://pjreddie.com/media/files/yolov3-tiny.weights

from PIL import Image
Image.open('darknet/data/kite.jpg')

! cd darknet; ./darknet detect cfg/yolov3-tiny.cfg ../yolov3-tiny.weights data/dog.jpg

from PIL import Image
Image.open('darknet/predictions.jpg')

